version: '3'

services:
  rails:
    image: ruby:3.3.3-alpine3.19
    command: sh -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis

  vite:
    image: node:20-alpine
    command: sh -c "pnpm install && bin/vite dev"
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3036:3036'
    environment:
      - NODE_ENV=development

  sidekiq:
    image: ruby:3.3.3-alpine3.19
    command: sh -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=chatwoot_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
